%% Clear Matlab
clear all;
close all;
clc;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% 3km %%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Add Paths to Scripts and Data folders
addpath('...');

load('Gwater_Owner_3km_BW.mat');
load('Gwater_Owner_3km_HW.mat');
load('Pwater_Owner_3km_BW.mat');
load('Pwater_Owner_3km_HW.mat');


%%
% -------------- Black - White -------------- %
figure(1)
hold all
% -------------- Gwater -------------- %
F1 = plot(Gwater_Owner_3km_BW(:,1),...
    Gwater_Owner_3km_BW(:,2),...
    'LineWidth',1.4,'color','b');
patch([Gwater_Owner_3km_BW(:,1)' ...
    fliplr(Gwater_Owner_3km_BW(:,1)')], ...
    [Gwater_Owner_3km_BW(:,3)' ...
    fliplr(Gwater_Owner_3km_BW(:,4)')], ...
    'b','FaceAlpha',0.6);
% -------------- Pwater -------------- %
F2 = plot(Pwater_Owner_3km_BW(:,1),...
    Pwater_Owner_3km_BW(:,2),'--',...
    'LineWidth',1.4,'color','b');
patch([Pwater_Owner_3km_BW(:,1)' ...
    fliplr(Pwater_Owner_3km_BW(:,1)')], ...
    [Pwater_Owner_3km_BW(:,3)' ...
    fliplr(Pwater_Owner_3km_BW(:,4)')], ...
    'b','FaceAlpha',0.3);
hold off
ylim([-0.1,0.9])
legend([F1 F2], ...
    'Gwater','Pwater','Location','NE','Fontsize',10)
ylabel('Black - White','FontSize',10)
xlabel('Income (in $1000)','FontSize',10)
title('Black vs. White, Owner',...
    'FontSize',10)
% saveas(gcf,'HogsDiff_Water_BW_owner_3km.png')

%%
% -------------- His - White -------------- %
figure(2)
hold all
% -------------- Gwater -------------- %
F1 = plot(Gwater_Owner_3km_HW(:,1),...
    Gwater_Owner_3km_HW(:,2),...
    'LineWidth',1.4,'color','r');
patch([Gwater_Owner_3km_HW(:,1)' ...
    fliplr(Gwater_Owner_3km_HW(:,1)')], ...
    [Gwater_Owner_3km_HW(:,3)' ...
    fliplr(Gwater_Owner_3km_HW(:,4)')], ...
    'r','FaceAlpha',0.6);
% -------------- Pwater -------------- %
F2 = plot(Pwater_Owner_3km_HW(:,1),...
    Pwater_Owner_3km_HW(:,2),'--',...
    'LineWidth',1.4,'color','r');
patch([Pwater_Owner_3km_HW(:,1)' ...
    fliplr(Pwater_Owner_3km_HW(:,1)')], ...
    [Pwater_Owner_3km_HW(:,3)' ...
    fliplr(Pwater_Owner_3km_HW(:,4)')], ...
    'r','FaceAlpha',0.2);
hold off
ylim([-0.1,0.9])
legend([F1 F2], ...
    'Gwater','Pwater','Location','NE','Fontsize',10)
ylabel('His - White','FontSize',10)
xlabel('Income (in $1000)','FontSize',10)
title('His vs. White, Owner',...
    'FontSize',10)
% saveas(gcf,'HogsDiff_Water_HW_owner_3km.png')

